source 'https://rubygems.org'

gem "sinatra", "~> 1.4.5"
gem "slim", "~> 3.0.3"
gem "puma"
gem 'league', :path => '../league'

group :development do
  gem "rspec", "~> 3.2.0"
  gem "sinatra-reloader", "~> 1.0"
end
